/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Cinnamine3D (https://sketchfab.com/LordCinn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-ready-scifi-helmet-ff4c8308932447ac9ac831155fb63992
Title: GAME READY SCIFI HELMET
*/

import * as THREE from "three";
import type { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane008_rubber_0: THREE.Mesh;
    Plane008_metal_0: THREE.Mesh;
    Plane008_main_0: THREE.Mesh;
    Plane008_maskfront_0: THREE.Mesh;
    Plane008_secondmain_0: THREE.Mesh;
    Plane008_visor_0: THREE.Mesh;
    Plane008_metal2_0: THREE.Mesh;
    Plane008_emit_0: THREE.Mesh;
  };
  materials: {
    rubber: THREE.MeshStandardMaterial;
    metal: THREE.MeshStandardMaterial;
    main: THREE.MeshStandardMaterial;
    maskfront: THREE.MeshStandardMaterial;
    secondmain: THREE.MeshStandardMaterial;
    visor: THREE.MeshStandardMaterial;
    metal2: THREE.MeshStandardMaterial;
    emit: THREE.MeshStandardMaterial;
  };
};

export default function ScifiHelmet(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/game_ready_scifi_helmet.glb"
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_rubber_0.geometry}
          material={materials.rubber}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_metal_0.geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_main_0.geometry}
          material={materials.main}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_maskfront_0.geometry}
          material={materials.maskfront}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_secondmain_0.geometry}
          material={materials.secondmain}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_visor_0.geometry}
          material={materials.visor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_metal2_0.geometry}
          material={materials.metal2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_emit_0.geometry}
          material={materials.emit}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/game_ready_scifi_helmet.glb");
